-----
-- Restore [AdventureWorks2016_EXT]
-- This is for the second server, aka the TARGET. Placing a stub of the database 
-- created in the first script here. 
--
-- All I did was "Script Database as CREATE" in SSMS to generate the below code

USE [master]
GO

/****** Object:  Database [AdventureWorks2016_EXT]    Script Date: 3/14/2022 9:55:30 AM ******/
CREATE DATABASE [AdventureWorks2016_EXT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorks2016_EXT_Data', FILENAME = N'M:\mssql\data\AdventureWorks2016_EXT_Data.mdf' , SIZE = 395584KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB ), 
 FILEGROUP [AdventureWorks2016_EXT_mod] CONTAINS MEMORY_OPTIMIZED_DATA  DEFAULT
( NAME = N'AdventureWorks2016_EXT_mod', FILENAME = N'M:\mssql\data\AdventureWorks2016_EXT_mod' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'AdventureWorks2016_EXT_Log', FILENAME = N'M:\mssql\log\AdventureWorks2016_EXT_Log.ldf' , SIZE = 182272KB , MAXSIZE = 2048GB , FILEGROWTH = 16384KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdventureWorks2016_EXT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET ANSI_NULLS ON 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET ANSI_PADDING ON 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET ARITHABORT ON 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET  MULTI_USER 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET QUERY_STORE = ON
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 31), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 5, MAX_STORAGE_SIZE_MB = 1024, QUERY_CAPTURE_MODE = ALL, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

USE [AdventureWorks2016_EXT]
GO

EXEC [AdventureWorks2016_EXT].sys.sp_addextendedproperty @name=N'MS_Description', @value=N'AdventureWorks 2014 Sample OLTP Database' 
GO

USE [master]
GO

ALTER DATABASE [AdventureWorks2016_EXT] SET  READ_WRITE 
GO

